### PR TITLE
Responsive design and templating fixes

### PR DESCRIPTION
**Pull request by rusel1989**
This PR was requested by @lukascpex from CPEX, it contains changes and improvements we have made specifically for CPEX. All tests are green and it should support not contain any breaking changes

This PR includes:

* Responsive design fixes
* Theming fixes
* Automatic code formatting with prettier
* Break down large components into smaller ones
* Small fixes and improvements

### CODE REVIEW

**Comment by shackijj** [comment]
Hello @samtingleff,
Could you please request my review on this PR?
Also, I'd like to know the current browser support for this library.

**Comment by samtingleff** [comment]
Hi @shackijj, I believe our goal for browser support is provided in an attachment to #12. I've attempted to summarize here.

* Chrome for Android
* Chrome 49+
* Safari iPhone/iPad
* Firefox 52+
* IE 11.0
* Edge 16+
* Safari 11+
* Samsung Internet 6+
* Opera 51+

In general we should expect to be pragmatic and if there are especially difficult trade offs to be made for old browsers, it's probably worth a discussion.

**Comment by shackijj** [comment]
Hello @rusel1989, @samtingleff,

Could someone provide more detailed descriptions for these points?
> Responsive design fixes
Theming fixes
Small fixes and improvements

In my opinion, it'd be better if this PR contained less commits. I suggest creating a separate issue and a PR for each problem/feature. It's difficult to review so many changes at once. Moreover, these changes are not related directly to each other.

@rusel1989 Is possible to rebase this branch in order to move commits related to different features into separate branches? It seems like a very big change. 

I noticed that .jsx files are not checked by the linter. 
In order to solve this, we have to add "--ext .js,.jsx" to the lint command
```
    "lint": "eslint src test --ext .js,.jsx",
```
There are plenty of linting errors in .jsx files.

```
✖ 523 problems (488 errors, 35 warnings)
  486 errors, 2 warnings potentially fixable with the `--fix` option.
```

Also, one on the e2e tests fails

```
Started
F..................................

Failures:
1) different configurations Layout - Modal has a page title
  Message:
    Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, [class^=intro_title])
  Stack:
    NoSuchElementError: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, [class^=intro_title])
        at selenium_webdriver_1.promise.all.then (/Users/kshatskiy/open-source/cmp/node_modules/protractor/built/element.js:274:27)
        at ManagedPromise.invokeCallback_ (/Users/kshatskiy/open-source/cmp/node_modules/selenium-webdriver/lib/promise.js:1376:14)
        at TaskQueue.execute_ (/Users/kshatskiy/open-source/cmp/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/Users/kshatskiy/open-source/cmp/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/Users/kshatskiy/open-source/cmp/node_modules/selenium-webdriver/lib/promise.js:2927:27)
        at /Users/kshatskiy/open-source/cmp/node_modules/selenium-webdriver/lib/promise.js:668:7
        at <anonymous>
```

@samtingleff How about integrating CI and Github using the webhooks. It will allow us to see a result of the building job in PRs?

@rusel1989 Let's add e2e tests for the design problems' fixes.

**Comment by rusel1989** [comment]
We have discussed this PR @shackijj and decided to create smaller PRs at the points where we have merged feature branches in our internal repository

**Comment by samtingleff** [comment]
@shackijj on this topic
> How about integrating CI and Github using the webhooks. It will allow us to see a result of the building job in PRs?

I think we have this, no? Are you able to see builds at https://circleci.com/gh/digi-trust/cmp ?

**Pull request closed without merging**
